### ISSUE TITLE
二维码校验失败

### ISSUE THREAD

**Issue by Feb17** [louisyoungx/JD-SHOPPER#2]
[root@instance-20211027-1005 JD-SHOPPER]# python3 main.py

===== 注意 =====
使用前请按要求填写config.ini中的信息

功能列表：
 1.自动加购物车，缺货等待上架自动下单
 2.自动定时加购物车下单（普通商品，非秒杀抢购）

请选择:1
[2021-11-24 07:12:04] (spider.new_func): <INFO> waitForSell 需登陆后调用，开始扫码登陆
[2021-11-24 07:12:06] (login._get_qrcode): <INFO> 二维码获取成功，请打开京东APP扫描
MoTTY X11 proxy: Unsupported authorisation protocol

(eog:20608): Gtk-WARNING **: 07:12:06.939: cannot open display: localhost:10.0
[2021-11-24 07:12:07] (login._get_qrcode_ticket): <INFO> Code: 201, Message: 二维码未扫描，请扫描二维码
[2021-11-24 07:12:09] (login._get_qrcode_ticket): <INFO> Code: 201, Message: 二维码未扫描，请扫描二维码
[2021-11-24 07:12:11] (login._get_qrcode_ticket): <INFO> Code: 201, Message: 二维码未扫描，请扫描二维码
[2021-11-24 07:12:14] (login._get_qrcode_ticket): <INFO> Code: 201, Message: 二维码未扫描，请扫描二维码
[2021-11-24 07:12:16] (login._get_qrcode_ticket): <INFO> Code: 201, Message: 二维码未扫描，请扫描二维码
[2021-11-24 07:12:18] (login._get_qrcode_ticket): <INFO> Code: 201, Message: 二维码未扫描，请扫描二维码
[2021-11-24 07:12:21] (login._get_qrcode_ticket): <INFO> Code: 201, Message: 二维码未扫描，请扫描二维码
[2021-11-24 07:12:23] (login._get_qrcode_ticket): <INFO> Code: 201, Message: 二维码未扫描，请扫描二维码
[2021-11-24 07:12:25] (login._get_qrcode_ticket): <INFO> Code: 202, Message: 请手机客户端确认登录
[2021-11-24 07:12:28] (login._get_qrcode_ticket): <INFO> Code: 202, Message: 请手机客户端确认登录
[2021-11-24 07:12:30] (login._get_qrcode_ticket): <INFO> Code: 202, Message: 请手机客户端确认登录
[2021-11-24 07:12:32] (login._get_qrcode_ticket): <INFO> 已完成手机客户端确认
[2021-11-24 07:12:33] (login._validate_qrcode_ticket): <INFO> {'returnCode': 80}
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    waiter.waitForSell()
  File "/root/JD-SHOPPER/Core/spider.py", line 90, in new_func
    self.login_by_qrcode()
  File "/root/JD-SHOPPER/Core/spider.py", line 73, in login_by_qrcode
    self.qrlogin.login_by_qrcode()
  File "/root/JD-SHOPPER/Core/login.py", line 251, in login_by_qrcode
    raise SKException('二维码信息校验失败')
Core.exception.SKException: 二维码信息校验失败
[root@instance-20211027-1005 JD-SHOPPER]#

你好作者， 我又来了。
我是通过WinSCP 把qr_code.png 拉到本机进行查看扫码的。

**Comment by louisyoungx** [comment]
京东的二维码只能用本局域网内的手机扫码解锁，手机和服务器不在同一个局域网内扫码是不被京东允许的。
你的服务器不在本地的话，可以通过以下步骤运行：
> 1. 先在本地运行项目，扫码后关闭项目
> 2. 复制cookies/目录下你的cookie到你的服务器项目的cookies目录下
> 3. 运行服务器下项目

**Comment by louisyoungx** [comment]
如果没有其他问题，这个issue将在本周末关闭

**Comment by Feb17** [comment]
> 如果没有其他问题，这个issue将在本周末关闭

感谢，已解决
