### ISSUE TITLE
exe启动时报错（安装路径不能有中文）

### ISSUE THREAD

**Issue by Ruikoto** [louisyoungx/jd-shopper#40]
![image](https://user-images.githubusercontent.com/30781137/159154227-dcf358c0-c55e-4d01-9992-86e9e24b1d91.png)

```
Traceback (most recent call last):
  File "runserver.py", line 48, in <module>
  File "runserver.py", line 33, in running
  File "GUI\gui.py", line 27, in gui
    webview.start()
  File "webview\__init__.py", line 122, in start
  File "webview\guilib.py", line 101, in initialize
  File "webview\guilib.py", line 62, in try_import
  File "webview\guilib.py", line 52, in import_winforms
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "webview\platforms\winforms.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 43, in load
  File "clr_loader\wrappers.py", line 20, in __call__
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'
```

**Comment by sharusjz** [comment]
一样。

**Comment by louisyoungx** [comment]
我是在win11上打包的，用win10打开可能有点兼容性问题，我找台win10调试下吧

可以暂时用命令行和web版本

**Comment by MinezzZ** [comment]
路径中不要有中文

**Comment by septwolf1** [comment]
启动报错，但是可以用，我试了

**Comment by louisyoungx** [comment]
注意：安装路径中不能有中文字符🚫

比如 `C:/Users/someone/test/jd-shopper/` 目录可以运行

但是 `C:/Users/某人/测试/jd-shopper/` 运行会报错

---

目前的 `v1.2.1` 只支持win11版本，如果win10运行可能会有无法预知的错误

如果遇到打开客户端空白的情况，也可尝试在浏览器打开 `http://localhost:12021/`
